### PR TITLE
Revise and update the Fedora snapd information

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Note that this PR is currently blocked on the successful push of the following updates:

* Fedora 25: https://bodhi.fedoraproject.org/updates/FEDORA-2017-4f8de51e27
* Fedora 26: https://bodhi.fedoraproject.org/updates/FEDORA-2017-f24fd67e3a

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@caldav The proposed updates have the requisite karma and will be rolled out by Monday.

**Comment by caldav** [comment]
Thanks for the update @Conan-Kudo, will be merged and deployed on monday

**Comment by Conan-Kudo** [comment]
@caldav The updates have hit the mirror network now.

**Comment by caldav** [comment]
ty!

**Pull request merged**
