### PR TITLE
Put the language guides in a grid with logos

### PR DESCRIPTION
**Pull request by evandandrea**
screen shot 2017-09-20 at 15 02 52

Requires https://github.com/canonical-websites/snapcraft.io/pull/381

### CODE REVIEW

**Comment by evandandrea** [comment]
I'm not sold on the image for "pre-built apps." Suggestions welcome.

**Comment by sergiusens** [comment]
Not sure about pre-build apps, but I'd put the "Languages" index entry right below "Your first snap" and change it to "Language Guides" to convey what it is in a more direct manner.

btw, +1 on the initiative of using images.

**Comment by caldav** [comment]
Looking good. What about using the default app/package icon from Adwaita (GNOME's default)? 
https://github.com/GNOME/adwaita-icon-theme/blob/master/src/fullcolor/application-x-executable.svg 
or https://github.com/GNOME/adwaita-icon-theme/blob/master/src/fullcolor/packages.svg

**Comment by evandandrea** [comment]
@caldav we'd have to attribute GNOME in the footer if we used that, correct?

**Comment by caldav** [comment]
[Correct](https://github.com/GNOME/adwaita-icon-theme/blob/master/COPYING). CC-BY-SA
 
> When attributing the artwork, using "GNOME Project" is enough.
Please link to http://www.gnome.org where available.

**Comment by evandandrea** [comment]
@caldav done as https://github.com/CanonicalLtd/snappy-docs/pull/104

**Comment by caldav** [comment]
@evandandrea @sergiusens I'll do the nav change in another PR. Merging this one.

**Pull request merged**
