### PR TITLE
Update Fedora snapd to 2.27.6

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This is pending the push of the following Bodhi updates:

* Fedora 27: https://bodhi.fedoraproject.org/updates/FEDORA-2017-4546b9dd38
* Fedora 26: https://bodhi.fedoraproject.org/updates/FEDORA-2017-8ef8c9e6c2
* Fedora 25: https://bodhi.fedoraproject.org/updates/FEDORA-2017-d699df2619

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@caldav This is going into the repositories tomorrow.

**Comment by caldav** [comment]
Thanks @Conan-Kudo, tracking

**Comment by Conan-Kudo** [comment]
@caldav Fedora 27's update is blocked on the Go/No-Go meeting for the beta. Since it's been delayed a week, _all_ updates stay in updates-testing. That said, updates-testing is enabled by default on pre-release Fedora, so it's effectively available anyway.

**Comment by Conan-Kudo** [comment]
@caldav The Fedora 27 update synchronized out to the stable repositories now.

**Pull request merged**
